### ISSUE TITLE
resp2.Any does not check for resp.Marshaler 

### ISSUE THREAD

**Issue by nussjustin** [mediocregopher/radix#74] opened 2019-03-02 14:19 UTC
Just stumbled over this one, as it bit me while writing some tests.

`resp2.Any` already handles types implementing `resp.Unmarshaler` when unmarshalling but does not do the same for types implementing `resp.Marshaler` when marshalling.

**Comment by mediocregopher** [comment] 2019-03-02 17:39
This is a known issue, and is documented on the Any type, as well as on FlatCmd. The problem is that I never quite figured out how to deal with the interplay between a user marshaling their own type and Any needing to support the `MarshalBulkString` and `MarshalNoArrayHeaders`. Each one would require re-decoding whatever the user returned and then re-encoding it again, which seems extremely impractical. And also Any's `NumElems` method would need to do something similar. It all seemed like more effort than necessary, and a user is capable of writing their own Marshaler I figure their capable of wrapping it into a `CmdAction` or whatever too.

**Comment by nussjustin** [comment] 2019-03-04 11:47
> This is a known issue, and is documented on the Any type, as well as on FlatCmd.

Come on, who reads the docs? That's boring. Also the "New Issue" buttons always looks like it wants to be clicked. 

> The problem is that I never quite figured out how to deal with the interplay between a user marshaling their own type and Any needing to support the MarshalBulkString and MarshalNoArrayHeaders fields. Each one would require re-decoding whatever the user returned and then re-encoding it again, which seems extremely impractical. 

I agree that there doesn't seem to be a simple solution here and I didn't think about these options.

> And also Any's NumElems method would need to do something similar.

Btw. the formatted comment on [GoDoc](https://godoc.org/github.com/mediocregopher/radix/resp/resp2#Any.NumElems) is missing a few line breaks. These lines should probably be indented (like [here](https://godoc.org/encoding/gob#hdr-Types_and_Values)) 

> It all seemed like more effort than necessary, and if a user is capable of writing their own Marshaler I figure they're capable of wrapping it into a CmdAction or whatever too.

I needed to marshal multiple values for some tests and wanted to avoid without wrapping most of them in `resp.Any`. In the end I went with a manual check on `resp.Marshaler`: https://github.com/nussjustin/radixutil/blob/62e74e1/stream/stream_test.go#L20-L39

It would still be nice to have `resp.Any` be able to handle `resp.Marsahler`, but given the complexity of a solution I'd be ok with just ignoring this for now.

**Comment by mediocregopher** [comment] 2020-05-18 01:27
This is included in the v4 proposal at #212 so I'm going to go ahead and close it.

**Closed by mediocregopher** 2020-05-18 01:27 UTC
