### ISSUE TITLE
Nilpointer

### ISSUE THREAD

**Issue by Bysmyyr** [mediocregopher/radix#273] opened 2021-04-28 06:21 UTC
Hi,

it crash by nilpointer time to time, especially when running tests with debugger:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc6eb62]

goroutine 15 [running]:
github.com/mediocregopher/radix/v4.(*poolConn).EncodeDecode(0x0, 0x15d5020, 0xc00088e7e0, 0x1380480, 0xc0001c8150, 0x1380480, 0xc0001c8150, 0x0, 0x0)
	/home/olli/go/pkg/mod/github.com/mediocregopher/radix/v4@v4.0.0-beta.1/pool.go:34 +0x42
github.com/mediocregopher/radix/v4.(*cmdAction).Perform(0xc0001c8150, 0x15d5020, 0xc00088e7e0, 0x15d5420, 0x0, 0x0, 0x0)
	/home/olli/go/pkg/mod/github.com/mediocregopher/radix/v4@v4.0.0-beta.1/action.go:270 +0xa2
github.com/mediocregopher/radix/v4.(*poolConn).Do(0x0, 0x15d5020, 0xc00088e7e0, 0x15c8340, 0xc0001c8150, 0x0, 0x0)
	/home/olli/go/pkg/mod/github.com/mediocregopher/radix/v4@v4.0.0-beta.1/pool.go:45 +0x74
github.com/mediocregopher/radix/v4.(*pool).useSharedConn.func1(0x0, 0x0)
	/home/olli/go/pkg/mod/github.com/mediocregopher/radix/v4@v4.0.0-beta.1/pool.go:407 +0x18e
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).WithRLock(0xc0000a6fc0, 0xc00054dc58, 0x0, 0x0)
	/home/olli/go/pkg/mod/github.com/mediocregopher/radix/v4@v4.0.0-beta.1/internal/proc/proc.go:104 +0xf2
github.com/mediocregopher/radix/v4.(*pool).useSharedConn(0xc00013dd40, 0x15d5020, 0xc00088e7e0, 0x15c8340, 0xc0001c8150, 0x0, 0x0)
	/home/olli/go/pkg/mod/github.com/mediocregopher/radix/v4@v4.0.0-beta.1/pool.go:400 +0x145
github.com/mediocregopher/radix/v4.(*pool).Do(0xc00013dd40, 0x15d5020, 0xc00088e7e0, 0x15c8340, 0xc0001c8150, 0x0, 0x0)
	/home/olli/go/pkg/mod/github.com/mediocregopher/radix/v4@v4.0.0-beta.1/pool.go:429 +0xeb
github.com/mediocregopher/radix/v4.poolConfig.new.func2(0x15d5020, 0xc00088e7e0)
	/home/olli/go/pkg/mod/github.com/mediocregopher/radix/v4@v4.0.0-beta.1/pool.go:214 +0x19e
github.com/mediocregopher/radix/v4.(*pool).atIntervalDo.func1(0x15d4fa0, 0xc0002b17c0)
	/home/olli/go/pkg/mod/github.com/mediocregopher/radix/v4@v4.0.0-beta.1/pool.go:293 +0x1b7
github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run.func1(0xc0002a1b40, 0xc0000a6fc0)
	/home/olli/go/pkg/mod/github.com/mediocregopher/radix/v4@v4.0.0-beta.1/internal/proc/proc.go:45 +0x48
created by github.com/mediocregopher/radix/v4/internal/proc.(*Proc).Run
	/home/olli/go/pkg/mod/github.com/mediocregopher/radix/v4@v4.0.0-beta.1/internal/proc/proc.go:44 +0x6b

Debugger finished with exit code 0
```

**Comment by nussjustin** [comment] 2021-05-02 13:45
The `*poolConn` returned from the `*poolConnColl`seems to be `nil`. `nil` should only be possible if there is a problem with synchronization with a call to either `remove` or `popBack`. `remove` is used only once and correctly takes a write lock. `popBack` is used twice, one time with a write lock and another time when closing the pool. When closing no write lock is obtained, but at that point all goroutines that belong to it's proc, including the one causing the error, have exited (guaranteed by a `sync.WaitGroup`).

Thus I don't see how this could happen other than when there is a data race.

Have you tried running your tests with the `-race` flag?

**Comment by Bysmyyr** [comment] 2021-05-24 09:31
@nussjustin thanks for you reply. -race did not give anything

**Comment by nussjustin** [comment] 2021-05-24 10:39
Unfortunately we can't really do much to help here without code that reproduces the problem.

Is this problem easily reproducible for you? If yes, then could you try running your program with [rr](https://rr-project.org/). This will create a recording which you can then debug using [delve](https://github.com/go-delve/delve) (if you are using Jetbrains Goland, support for rr is already built in and you should be able to just tell Goland to record and debug your program).

When debugging the recording you can not only go forwards but also backwards in execution which should help you find the cause.

**Comment by Bysmyyr** [comment] 2021-05-24 12:23
@nussjustin It happens always when I step my code it with normal debugger -> rr does not help as it newer fail there. I can try to produce some example

**Comment by mediocregopher** [comment] 2021-07-17 17:02
@Bysmyyr are you still experiencing this? If not I'd like to close the issue.

**Comment by alexsniffin** [comment] 2021-07-20 17:31
Hello @mediocregopher @nussjustin, I ran into this same issue on v4.0.0-beta.1 when I was performing a load test. It seems that when the context to my requests are reaching the deadline and being canceled it was closing the connection. Quickly glancing over my logs it seems a lot of connections were closed due to context deadline right before this panic occurred.

**Comment by mediocregopher** [comment] 2021-07-26 22:57
@alexsniffin can you try your load test with the tip of the `v4` branch? There's been some fixes in pool_conn_coll since beta.1

**Comment by mediocregopher** [comment] 2021-10-14 00:12
I'm going to close out this issue, feel free to re-open if you're still encountering this issue on the tip of `v4`

**Closed by mediocregopher** 2021-10-14 00:12 UTC

**Comment by Bysmyyr** [comment] 2021-10-14 10:23
@mediocregopher sorry, I changed my job so this is not in my table anymore. Thanks anyway!
