### ISSUE TITLE
PubSubConn.Ping blocks

### ISSUE THREAD

**Issue by artyom** [mediocregopher/radix#213] opened 2020-06-02 16:05 UTC
go version go1.14.4 darwin/amd64, although tested and reproduced on linux/amd64 as well.

Package version is v3.5.1.

Documentation has [an example for PubSub](https://pkg.go.dev/github.com/mediocregopher/radix/v3?tab=doc#example-PubSub):

	...
	// Subscribe to a channel called "myChannel". All publishes to "myChannel"
	// will get sent to msgCh after this
	msgCh := make(chan PubSubMessage)
	if err := ps.Subscribe(msgCh, "myChannel"); err != nil {
		panic(err)
	}
	
	for msg := range msgCh {
		log.Printf("publish to channel %q received: %q", msg.Channel, msg.Message)
	}

This example, however, does not make it clear how to handle underlying connections issues — if connection dies for some reason, msgCh won't be closed, and range loop will stuck forever.

My straightforward solution to this was to rely on [the PubSubConn contract](https://pkg.go.dev/github.com/mediocregopher/radix/v3?tab=doc#PubSubConn) saying "All methods are threadsafe and non-blocking", and to introduce periodic [Ping call](https://pkg.go.dev/github.com/mediocregopher/radix/v3?tab=doc#PubSubConn.Ping) like this:

	ticker := time.NewTicker(5 * time.Second)
	defer ticker.Stop()
	for {
		select {
		case <-ticker.C:
			if err := conn.Ping(); err != nil {
				return err // connection is dead, break receive loop
			}
		case msg := <-msgCh:
			log.Printf("publish to channel %q received: %q", msg.Channel, msg.Message)
		}
	}

Unfortunately, this approach revealed an issue of Ping method blocking forever, even if underlying radix.Conn was created with low timeouts.

Please see code illustrating this case at <https://gist.github.com/artyom/5ec1cf2ad45b2b31d869df1ef0f7aee6#file-main-go>. It spawns goroutine receiving from the pubsub channel with periodic Ping calls like above, another goroutine publishing messages, and another goroutine tracking number of receives vs publishes and crashing program when they diverge.

	¶ go run -race . localhost:6379
	2020/06/02 18:09:29 send vs receive drift 0
	2020/06/02 18:09:31 send vs receive drift 0
	2020/06/02 18:09:33 send vs receive drift 0
	2020/06/02 18:09:35 send vs receive drift 0
	2020/06/02 18:09:37 send vs receive drift 0
	2020/06/02 18:09:39 send vs receive drift 0
	2020/06/02 18:09:41 send vs receive drift 0
	2020/06/02 18:09:43 send vs receive drift 100
	2020/06/02 18:09:45 send vs receive drift 300
	2020/06/02 18:09:47 send vs receive drift 500
	2020/06/02 18:09:49 send vs receive drift 700
	2020/06/02 18:09:51 send vs receive drift 900
	2020/06/02 18:09:53 send vs receive drift 1100
	panic: drift is too big, receiver likely stuck
	
	goroutine 6 [running]:
	main.run.func3(0x0, 0x0)
		radix-bug/main.go:99 +0x2fc
	golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0000768a0, 0xc00000e300)
		golang.org/x/sync@v0.0.0-20200317015054-43a5402ce75a/errgroup/errgroup.go:57 +0x86
	created by golang.org/x/sync/errgroup.(*Group).Go
		golang.org/x/sync@v0.0.0-20200317015054-43a5402ce75a/errgroup/errgroup.go:54 +0x74
	
	goroutine 1 [semacquire]:
	sync.runtime_Semacquire(0xc0000768b0)
		runtime/sema.go:56 +0x42
	sync.(*WaitGroup).Wait(0xc0000768a8)
		sync/waitgroup.go:130 +0xd4
	golang.org/x/sync/errgroup.(*Group).Wait(0xc0000768a0, 0xc00000e300, 0x1415780)
		golang.org/x/sync@v0.0.0-20200317015054-43a5402ce75a/errgroup/errgroup.go:40 +0x43
	main.run(0x7ffeefbffa7e, 0xe, 0x1, 0x1)
		radix-bug/main.go:104 +0x4e2
	main.main()
		radix-bug/main.go:22 +0x148
	
	goroutine 4 [select]:
	main.run.func1(0x0, 0x0)
		radix-bug/main.go:44 +0x276
	golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0000768a0, 0xc0000768d0)
		golang.org/x/sync@v0.0.0-20200317015054-43a5402ce75a/errgroup/errgroup.go:57 +0x86
	created by golang.org/x/sync/errgroup.(*Group).Go
		golang.org/x/sync@v0.0.0-20200317015054-43a5402ce75a/errgroup/errgroup.go:54 +0x74
	
	goroutine 5 [chan receive]:
	github.com/mediocregopher/radix/v3.(*pubSubConn).do(0xc0000ac100, 0x1, 0x13b4998, 0x4, 0x0, 0x0, 0x0, 0xc00028a060, 0xc00018fee0)
		github.com/mediocregopher/radix/v3@v3.5.1/pubsub.go:332 +0x1ad
	github.com/mediocregopher/radix/v3.(*pubSubConn).Ping(0xc0000ac100, 0x0, 0x0)
		github.com/mediocregopher/radix/v3@v3.5.1/pubsub.go:459 +0xe0
	main.run.func2(0x0, 0x0)
		radix-bug/main.go:77 +0x58b
	golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0000768a0, 0xc000076900)
		golang.org/x/sync@v0.0.0-20200317015054-43a5402ce75a/errgroup/errgroup.go:57 +0x86
	created by golang.org/x/sync/errgroup.(*Group).Go
		golang.org/x/sync@v0.0.0-20200317015054-43a5402ce75a/errgroup/errgroup.go:54 +0x74
	
	goroutine 24 [chan send]:
	github.com/mediocregopher/radix/v3.(*pubSubConn).publish(0xc0000ac100, 0x13b5189, 0x7, 0x0, 0x0, 0xc000281000, 0xc, 0xc000281010, 0x7, 0x7)
		github.com/mediocregopher/radix/v3@v3.5.1/pubsub.go:302 +0x1fb
	github.com/mediocregopher/radix/v3.(*pubSubConn).spin(0xc0000ac100)
		github.com/mediocregopher/radix/v3@v3.5.1/pubsub.go:320 +0x2b9
	created by github.com/mediocregopher/radix/v3.newPubSub
		github.com/mediocregopher/radix/v3@v3.5.1/pubsub.go:266 +0x1d4
	
	goroutine 25 [semacquire]:
	sync.runtime_SemacquireMutex(0xc0000ac13c, 0x900000000, 0x1)
		runtime/sema.go:71 +0x47
	sync.(*Mutex).lockSlow(0xc0000ac138)
		sync/mutex.go:138 +0x1c1
	sync.(*Mutex).Lock(0xc0000ac138)
		sync/mutex.go:81 +0x7d
	github.com/mediocregopher/radix/v3.(*pubSubConn).Ping(0xc0000ac100, 0x0, 0x0)
		github.com/mediocregopher/radix/v3@v3.5.1/pubsub.go:456 +0x6a
	github.com/mediocregopher/radix/v3.newPubSub.func1(0xc0000ac100)
		github.com/mediocregopher/radix/v3@v3.5.1/pubsub.go:275 +0x103
	created by github.com/mediocregopher/radix/v3.newPubSub
		github.com/mediocregopher/radix/v3@v3.5.1/pubsub.go:271 +0x1f6
	
	goroutine 8 [select]:
	github.com/mediocregopher/radix/v3.(*pipeliner).reqLoop(0xc000106420)
		github.com/mediocregopher/radix/v3@v3.5.1/pipeliner.go:149 +0x2be
	github.com/mediocregopher/radix/v3.newPipeliner.func1(0xc000106420)
		github.com/mediocregopher/radix/v3@v3.5.1/pipeliner.go:68 +0x73
	created by github.com/mediocregopher/radix/v3.newPipeliner
		github.com/mediocregopher/radix/v3@v3.5.1/pipeliner.go:66 +0x1ff
	
	goroutine 9 [select]:
	github.com/mediocregopher/radix/v3.(*Pool).atIntervalDo.func1(0xc000186000, 0x3b9aca00, 0xc000050830)
		github.com/mediocregopher/radix/v3@v3.5.1/pool.go:445 +0x1e5
	created by github.com/mediocregopher/radix/v3.(*Pool).atIntervalDo
		github.com/mediocregopher/radix/v3@v3.5.1/pool.go:440 +0x85
	
	goroutine 10 [select]:
	github.com/mediocregopher/radix/v3.(*Pool).atIntervalDo.func1(0xc000186000, 0x3b9aca00, 0xc000050840)
		github.com/mediocregopher/radix/v3@v3.5.1/pool.go:445 +0x1e5
	created by github.com/mediocregopher/radix/v3.(*Pool).atIntervalDo
		github.com/mediocregopher/radix/v3@v3.5.1/pool.go:440 +0x85
	
	goroutine 11 [select]:
	github.com/mediocregopher/radix/v3.(*Pool).atIntervalDo.func1(0xc000186000, 0x3b9aca00, 0xc000050850)
		github.com/mediocregopher/radix/v3@v3.5.1/pool.go:445 +0x1e5
	created by github.com/mediocregopher/radix/v3.(*Pool).atIntervalDo
		github.com/mediocregopher/radix/v3@v3.5.1/pool.go:440 +0x85
	exit status 2

This code reproduces blocking behavior of Ping method in under 30 seconds, the likelihood of this seems to be highest when Ping method is called on schedule matching internal keepalive ping loop of pubSubConn:

https://github.com/mediocregopher/radix/blob/08554c470ea586a496d7b0e46288d6e7cdd20d2b/pubsub.go#L271-L279

Please notice that code uses [low timeouts in radix.Dial call](https://gist.github.com/artyom/5ec1cf2ad45b2b31d869df1ef0f7aee6#file-main-go-L56-L59), which does not seem to make any difference in Ping being blocked.

**Comment by artyom** [comment] 2020-06-02 16:37
I took a look at the [pubSubConn.spin method](https://github.com/mediocregopher/radix/blob/08554c470ea586a496d7b0e46288d6e7cdd20d2b/pubsub.go#L306-L322) and see that what I observe is a designed behavior. I added some prints around `else if errors.Is(err, errNotPubSubMessage)` branch:

https://github.com/mediocregopher/radix/blob/08554c470ea586a496d7b0e46288d6e7cdd20d2b/pubsub.go#L313-L315

and confirmed that it was called right before my program observed Ping as blocked.

As pubSubConn.spin method interleaves PubSubConn method results delivery with pubsub messages delivery to subscriber channels, documentation can be improved in this regards, probably [somewhere around this line](https://github.com/mediocregopher/radix/blob/08554c470ea586a496d7b0e46288d6e7cdd20d2b/pubsub.go#L184-L185):

> NOTE if any channels block when being written to they will block all other channels from receiving a publish.

My snippet from above can be changed to non-blocking like this:

	errCh := make(chan error, 1)
	go func() {
		defer close(errCh)
		ticker := time.NewTicker(5 * time.Second)
		defer ticker.Stop()
		for range ticker.C {
			if err := conn.Ping(); err != nil {
				select {
				case errCh <- err:
				default:
				}
				return
			}
		}
	}()
	for {
		select {
		case err := <-errCh:
			return err // connection is dead, break receive loop
		case msg := <-msgCh:
			log.Printf("publish to channel %q received: %q", msg.Channel, msg.Message)
		}
	}

This code does not block the spin loop.

**Comment by mediocregopher** [comment] 2020-06-06 15:05
Hello @artyom thanks for the in-depth feedback :) As far as I can tell PuSubConn is behaving as intended, there's just some documentation improvements which could be made:

* Ping does indeed block, and would not be useful if it didn't, so that line `All methods are threadsafe and non-blocking` is in error.

* Your issue with your `msgCh` not being read from due to the Ping blocking and causing a lockup is probably something that's easy to accidentally run into, since it's not obvious what's happening unless you dig into the source like you did. I'll update the example to include a periodic Ping.

**Comment by mediocregopher** [comment] 2020-06-06 15:21
Fixed by commit 6534c19.

Feel free to re-open the issue if you have any other questions, thanks again :)

**Closed by mediocregopher** 2020-06-06 15:21 UTC
