### ISSUE TITLE
Ipv6 address 

### ISSUE THREAD

**Issue by jaivas** [mediocregopher/radix#288] opened 2021-07-01 16:46 UTC
with ipv6 address, connecting to redis cluster specifying hostName:port e.g. radix.NewCluster("redis.ndp.svc.cluster.local:6379")
fails with error - dial tcp: address 8ffd:50::d4ea:6379: too many colons in address"
The expected ipv6 address format with port is [8ffd:50::d4ea]:6379. -not 8ffd:50::d4ea:6379 - -missing -[ ] causing it

**Comment by jaivas** [comment] 2021-07-16 15:58
Workaround ...

**Comment by mediocregopher** [comment] 2021-07-17 18:04
@jaivas when you get a chance, can you post what `CLUSTER SLOTS` looks like on your cluster? I want to confirm the issue is what I think it is. I think the problem is that redis is reporting the IPs of the other nodes in the cluster with this incorrect formatting. I'm not able to replicate using direct calls to Dial with a hostname which resolves to an ipv6 address, so I can't think of where else this error would be coming from.

**Comment by jaivas** [comment] 2021-07-20 18:33
root@redis-0:/# redis-cli cluster slots
1) 1) (integer) 0
   2) (integer) 16383
   3) 1) "8ffd:50::d4eb"
      2) (integer) 6379
      3) "39b43ce0385b215347aea925d665f037dc3f13ab"

**Comment by mediocregopher** [comment] 2021-07-26 23:04
Thanks @jaivas, I just pushed a fix for this to master, can you try it out?

**Closed** 2021-07-26 23:03 UTC
