### ISSUE TITLE
v4: UnMarshalling error

### ISSUE THREAD

**Issue by aman1698** [mediocregopher/radix#308] opened 2022-02-14 13:53 UTC
`response returned from Conn: unexpected error on Conn: unmarshaling message off Conn: read tcp [::1]:65226-\u003e[::1]:6379: wsarecv: An existing connection was forcibly closed by the remote host.` 

`response returned from Conn: flushing write buffer: write tcp [::1]:59877->[::1]:6379: wsasend: An established connection was aborted by the software in your host machine.`

**Comment by mediocregopher** [comment] 2022-04-18 23:03
@aman1698 are you able to provide any context for this error? If you could include the version of radix you're using, whether or not the error is reproducible, and a test case if so, that'd be very helpful. Otherwise I'm going to have to close this because there's not much to go on.

**Closed as completed** 2022-06-30 15:45 UTC
