### ISSUE TITLE
pubsub does not work

### ISSUE THREAD

**Issue by saiisgod** [mediocregopher/radix#303] opened 2021-11-20 10:30 UTC
version: 4.0.0

I have find the ExamplePubSubConn doest not work. And I am pretty sure that this is a bug. 
Also I have changed some code to fix the bug. 
Since I donot know how to collaborate with others on github, I write the issue instead of pushing code.
Later I will try to push my code to your repo.

**Comment by padakuro** [comment] 2021-12-30 23:08
Just had the same problem with PubSub, where the call to `pconn.Next(ctx)` will force close the connection and fail. I tracked it down to an unexpected response.

* Redis version: **6.2.6 (ArchLinux)**
* Radix version: **github.com/mediocregopher/radix/v4 v4.0.0**

## Program to reproduce the issue

Basically the same as the pubsub example. Run it, it will crash instantly.

```go
package main

import (
	"context"
	"fmt"
	"github.com/mediocregopher/radix/v4"
)

func main() {
	ctx := context.Background()

	conn, err := radix.Dial(ctx, "tcp", "127.0.0.1:6379")
	if err != nil {
		panic(err)
	}

	ps := (radix.PubSubConfig{}).New(conn)
	if err := ps.Subscribe(ctx, "foo"); err != nil {
		panic(err)
	}

	for {
		msg, err := ps.Next(ctx)
		if err != nil {
			fmt.Println("PANIC - connection closed due to errNotPubSubMessage")
			panic(err)
		}

		fmt.Printf("msg recv: %s = %s\n", msg.Channel, string(msg.Message))
	}
}
```

## Error location

It will hit the default case and return the `errNotPubSubMessage` error, which will force close the connection.

https://github.com/mediocregopher/radix/blob/v4/pubsub.go#L116-L123

https://github.com/mediocregopher/radix/blob/c84f209e219a007e2bf607ab79ac751960b9b117/pubsub.go#L116-L123

## Quick fix

My quick fix was to add the two responses to the switch and discard the data. Not sure if this is how it should be handled or if there's more to it, but I hope this helps to pin it down.

```go
case "subscribe", "pong":
    m.Type = string(msgType.B)
    // discard rest
    for i := 1; i < numElems; i++ {
	if err := resp3.Unmarshal(br, nil, o); err != nil {
		return err
	}
    }
    return nil
```

**Comment by nussjustin** [comment] 2021-12-31 16:33
Without having looked at the code yet, is sounds like the `return errNotPubSubMessage` should be `return resp.ErrConnUsable{Err: errNotPubSubMessage}`. This way the connection would not be closed.

Also the code should never get a `PONG` there since the `PING`s are handled separately.

**Comment by padakuro** [comment] 2022-01-03 21:24
Yep, `resp.ErrConnUsable{Err: errNotPubSubMessage}` does work. Not sure where I got the PONG though, so most likely an error on my side.

**Comment by saiisgod** [comment] 2022-03-27 02:50
Happy to see it helps.
I fixed the bug.  The code is below
<img width="898" alt="image" src="https://user-images.githubusercontent.com/21364533/160264498-22606f2c-cacb-49cf-8101-87e96c2ca6b3.png">

**Comment by mediocregopher** [comment] 2022-04-18 23:20
This should be fixed by the above PR merge, will cut a new release momentarily.

**Closed as completed by mediocregopher** 2022-04-18 23:20 UTC
