### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by kataras** [mediocregopher/radix#184] opened 2020-02-09 21:41 UTC
Hello @mediocregopher,

First of all good job on this high-performant redis client. At iris web framework, we use that on [sessions](https://github.com/kataras/iris/blob/54ff8c7db9939d677fd1999ee533048792893207/_examples/sessions/database/redis/main.go#L27) as an optional redis driver for session database. We also use that on the [neffos real-time framework](https://github.com/kataras/neffos) for [scaling out](https://github.com/kataras/neffos/blob/37d0f3fa4ea5fd4115939f032296e1266bf618dc/_examples/scale-out/main.go#L14).

I've just got a `panic: send on closed channel` because of `newPubSuh->spin->publish` (radix v3.3.0). The full source code is located at: https://github.com/kataras/neffos/tree/master/_examples/scale-out which you can simply download and re-produce using `docker compose up`. Here is a screenshot:

![bug_radix](https://user-images.githubusercontent.com/22900943/74110419-24554600-4b95-11ea-9907-1254db720a25.png). The flow: 3 users join to the same namespace:room, 1 more join to the same namespace but different room. One of those 3 users sending a private message to the one which is not part of the room, the first two clients are disconnected, now close the rest 2 tabs and you will probably see the error.

The source code we use your library is located at: https://github.com/kataras/neffos/blob/master/stackexchange/redis/stackexchange_redis.go. Please review it and tell me if we miss-use your library, otherwise there is a high possibility that the radix package has a serious bug and we'll wait for a fix.

Thank you,
Gerasimos Maropoulos

**Comment by mediocregopher** [comment] 2020-02-10 01:28
Hi @kataras , thanks for writing up the issue. Looking through the source code, I _think_ I see one potential way this could be happening:

1) You call `Close` on the `PersistentPubSub` [here](https://github.com/kataras/neffos/blob/master/stackexchange/redis/stackexchange_redis.go#L174), then immediately close the subscribed `msgCh` channel (this is fine, you should be able to do this).

2) `PersistentPubSub` closes its interior `pubSubConn` [here](https://github.com/mediocregopher/radix/blob/master/pubsub_persistent.go#L250), just after closing a `closeCh`.

3) That `pubSubConn`, when closing, will close an `errCloseCh` [here](https://github.com/mediocregopher/radix/blob/master/pubsub.go#L356), if it's set. `PersistentPubSub` _does_ set that channel, so it can know when the `pubSubConn` disconnects. It receives on that channel [here](https://github.com/mediocregopher/radix/blob/master/pubsub_persistent.go#L135), along with the `closeCh` from step 2.

4) Ideally what should happen is that `PersistentPubSub` sees that the `closeCh` from 2 is closed first, which causes that go-routine to exit and nothing bad happens. _But_ if it sees the `errCloseCh` close first, it will call `refresh`, which will make a new `pubSubConn` that is subscribed to the `msgCh` which was closed in step 1, and the next time that gets written to it panics.

This whole section of code is quite messy, and could probably use a nice refactor. As a sanity check in the meantime could you apply the following diff and see if it alleviates the issue:

```
diff --git a/pubsub_persistent.go b/pubsub_persistent.go
index b043e18..316aad0 100644
--- a/pubsub_persistent.go
+++ b/pubsub_persistent.go
@@ -69,6 +69,11 @@ func (p *persistentPubSub) refresh() {
                go func() {
                        select {
                        case <-errCh:
+                               select {
+                               case <-p.closeCh:
+                                       return
+                               default:
+                               }
                                p.l.Lock()
                                // It's possible that one of the methods (e.g. Subscribe)
                                // already had the lock, saw the error, and called refresh. This
```

It is _note_ my intended fix (it's hella ugly), but it should at least tell us if this is actually the problem.

**Comment by kataras** [comment] 2020-02-10 09:46
Hello @mediocregopher,

Thanks for getting back to me. I've added the diff on local radix and I can't re-produce the panic now. Good job, should we wait a proper fix soon?

**Comment by mediocregopher** [comment] 2020-02-10 21:40
That's great to hear! I will work on some kind of proper fix in the near future, but I can't guarantee a timeframe. Hopefully in the next week or two.

**Comment by kataras** [comment] 2020-02-11 12:42
OK sounds fair, I will just add a replace directive to a fork with the temp fix. Please mention my name here when you fix it here as well. Again, thank you and keep up the awesome job, this pkg is the fastest redis client implementation written in Go.

**Comment by mediocregopher** [comment] 2020-02-13 05:21
@kataras I made a PR at https://github.com/mediocregopher/radix/pull/185 if you want to check it out. It includes a test case which reproduced the issue, so I'm fairly confident it works, but if you could double check with your code I'd appreciate it :)

**Comment by mediocregopher** [comment] 2020-02-19 17:50
@kataras I went ahead and merged that PR, if it for some reason doesn't work for you please re-open this and we'll figure it out. Thanks again!

**Closed by mediocregopher** 2020-02-19 17:50 UTC

**Comment by kataras** [comment] 2020-04-28 03:05
@mediocregopher I can confirm that the new v3.5.0 solves the particular issue. Good job Brian Picciano! I'll keep you posted if anything changes. Stay safe and in good health!

**Comment by mediocregopher** [comment] 2020-04-28 17:36
Great to hear, you stay safe as well :)
