### ISSUE TITLE
newCluster returns "connection refused" for no reason

### ISSUE THREAD

**Issue by jeffsaremi** [mediocregopher/radix#339] opened 2023-02-18 16:46 UTC
I'm using`github.com/mediocregopher/radix/v3 v3.6.0` version of your library.
Trying to do a very simple topology get. I am not sure if I'm using this function properly since there's not a single example of how it can be used on the Internet
```
  addr := os.Args[1]
  fmt.Println("addr=", addr)
  cluster, err := radix.NewCluster([]string{addr})
```
and I run it like this:
```
root@7403286178bf:/# /topo redis1:7000
addr= redis1:7000
Error: error connecting to 172.18.0.4:7000: dial tcp 172.18.0.4:7000: connect: connection refused

```
and at the same time I can use `netcat` from the same machine and get this!
```
root@7403286178bf:/# echo -e '*2\r\n$7\r\nCLUSTER\r\n$5\r\nNODES\r\n' | nc  redis1 7000
$771
45098ed3c4cb7f255fde2175fafe69eab8bac9d3 172.18.0.3:7000@17000 slave 32b0540f9be75d57b1fc3ff3d2a62bedde04e7c0 0 1676738234119 3 connected
eb69c07e4b256b9656cca595ef8c4b17124c54cd 172.18.0.6:7000@17000 slave e8a7fca203cc15fa8c58bbc4e3c4aacb821b426a 0 1676738235000 2 connected
3
...
```

**Comment by mediocregopher** [comment] 2023-02-21 16:26
Hey @jeffsaremi , your usage looks right to me. Can you maybe try doing `echo -e '*2\r\n$7\r\nCLUSTER\r\n$5\r\nNODES\r\n' | nc  172.18.0.4 7000` and see if that works? It could be that `redis1` is resolving to something different for go than for `nc` (go has weird DNS quirks).

**Comment by jeffsaremi** [comment] 2023-02-21 23:29
@mediocregopher  Yes I checked that and address resolution to be correct.

**Comment by mediocregopher** [comment] 2023-02-22 15:20
I'm not sure what the problem could be then, you may have to use something like tcpdump or wireshark to inspect the tcp stream and see what the difference is between your `nc` command and whatever your go program is doing.

**Comment by mediocregopher** [comment] 2023-07-30 09:09
@jeffsaremi I am going to go ahead and close this issue, please feel to re-open it if it seems the issue is indeed with radix.

**Closed as completed by mediocregopher** 2023-07-30 09:09 UTC
